### PR TITLE
Added Cypress tests for bar chart [#183479648]

### PR DESCRIPTION
**Pull request by dougmartin**
This tests both authoring and runtime.

The authoring tests just test that all the fields are present have the correct values.

The runtime test checks all the elements of the bar chart and includes both keyboard and mouse testing of the sliders.

### CODE REVIEW

**Comment by dougmartin** [comment]
@tejal-shah / @saravanan-udayakumar I'm not sure which of you would like to review the Cypress test for the bar chart that I just added so I tagged both of you.

**Comment by dougmartin** [comment]
I'm going to go ahead and merge this as there are other PRs that depend on it.

**Comment by tejal-shah** [comment]
@dougmartin , thanks for doing this. The tests look good to me.

**Comment by dougmartin** [comment]
@tejal-shah Thanks.  I ended up doing a follow on PR (https://github.com/concord-consortium/question-interactives/pull/253) to explicitly set the viewport width and height that Cypress uses - otherwise it seems to be a little flaky since to test dragging I have to move the mouse to a specific pixel coordinate on the screen.

**Pull request merged**
