### PR TITLE
Labbook: add thumbnail title to draw tool area

### PR DESCRIPTION
**Pull request by pjanik**
[#179583551]
Screenshot 2021-09-30 at 17 43 42

### CODE REVIEW

**Review by knowuh — APPROVED** [review]
Looks good, thanks

(I was wondering if `classNames` would handle `classNames(className, ..., ...)` by gracefully handling undefined, but I wasn't sure it would work)

**Comment by pjanik** [comment]
> (I was wondering if classNames would handle classNames(className, ..., ...) by gracefully handling undefined, but I wasn't sure it would work)

No, it needs to be a string. I tried this approach, but it'd look like that:

```javascript
if (!className) {
  className = "";
}
let finalClassName = classNames([css["thumbnail-title"]], {[css.empty]: empty, [className]: !!className });
```
and I thought it isn't very readable / clear. ;)

**Comment by kswenson** [comment]
> (I was wondering if `classNames` would handle `classNames(className, ..., ...)` by gracefully handling undefined, but I wasn't sure it would work)

Yes, `classNames` handles `null`/`undefined` gracefully.

**Comment by pjanik** [comment]
> > (I was wondering if `classNames` would handle `classNames(className, ..., ...)` by gracefully handling undefined, but I wasn't sure it would work)
> 
> Yes, `classNames` handles `null`/`undefined` gracefully.

Right, but as a value. Not as the property name - that's what I meant. In this particular case, the className variable acts as both.

**Pull request merged**
